services:
  - type: web
    name: gabbana-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python gabbana-budget.py
    plan: free
    autoDeploy: false
    pythonVersion: 3.11.0
